@echo off
cd /d %_NTBINDIR%\private
echo.
echo  xdbgsym.cmd - Debug Symbol Placer
echo.
echo  This script will copy all symbol files found in "%_NT386TREE%\*\" 
echo  to "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\"
echo.
echo THIS WILL REMOVE ANY OLD DEBUGGING SYMBOLS..
echo.
pause
rem Create folder if needed, set the source and destination for the symbols, and clean up old files before copy
if NOT exist "%_NT386TREE%\Symbols.pri\" mkdir "%_NT386TREE%\Symbols.pri\"
if NOT exist "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" mkdir "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\"
if exist "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" cd /d "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" && del * /S /Q
xcopy "%_NT386TREE%\dump\accounts.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\AddOnlineUser.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\address.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\alphabld.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\alphabnt.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\alphacmp.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\AlphaFog.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\AntiAlias.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ASEConv.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\AsyncWrite.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\AsyncXMO.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\AudConsole.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\AudioStress.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Auth.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\authtest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\autoupdd.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\autoupdo.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\AVPAckTest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\BackBufferScale.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\BackgroundMusic.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Ball.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\basic.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\basicrst.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\bees.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\BeginPush.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\BenchMark.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\BenMark.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\betarec.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Billboard.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Billbrd.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\billing.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\blend.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\BoxID.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\brainbox.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\btnpress.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\bump.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\BumpDemo.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\bumpduv1.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\bumpduv2.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\BumpEarth.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\BumpLens.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\bumpnrm0.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Cartoon.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\CDRip.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\cdtest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\certspy.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\chessbrd.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\clear.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\clearbug.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ClipMir.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Clipping.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\clockwrk.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\compress.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ContentDownload.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\coverage.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\cpx.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\CreateDevice.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Cubemap.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\cxonline.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\d3dapi.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DebugChannel.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DebugKeyboard.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\default.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\depthbuf.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dftest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DirectSoundCreate.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DirectSoundCreateBuffer.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DirectSoundCreateStream.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\diskRead.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\diskWrite.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DisplacementMap.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dlight.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DM3DScript.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DMAudioPath.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DMGrooveLevel.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DMMultiPass.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DMNotifications.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DMScript.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Dolphin.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DolphinClassic.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DolphinHDTV.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Dolphtst.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DotProduct3.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DsoundDRT.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dsp.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dtmtest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dukeprod.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dumpEEPROM.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dvdauth.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dvdcont.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dvdecc.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dvdenum.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dvdjumpcounter.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dvdkey.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dvdperf.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dvdperftest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\DVDPROD.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dvdservopage.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dvdtest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dvdverify.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\dxtnoise.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\edttst.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\emboss.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\EnumSoundtrack.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\enumtest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\EnvelopeGenerator.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\event.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Explosion.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\feedback.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\FieldRender.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\FileStream.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\fillrate.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Fire.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\FocusBlur.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\fog.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\framework.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\FresnelReflect.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Friends.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\FSAA.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\fsaaperf.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Fur.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\FuzzyTeapot.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\fvertex1.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\FXMultiPass.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Gamepad.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\gammarmp.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GetRStat.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GlobalFX.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\gradient.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GRate0RP.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GRate1AO.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GRate2M.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GRate3T.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GRate4E.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GRate5KA.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GRate6EC.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\green.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GRegion1.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GRegion2.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GRegion3.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\GRegionAll.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\hawk.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\hdenum.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\hdperf.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\hdperf_ll.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\hdperf_sw.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\hdrw.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\hdsetup.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\hdsit.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\hightide.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\HVSLaunch.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\hwharness.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\IBuffer.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\innrloop.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\installer.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\irrem.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\leak.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Lighting.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\lightmap.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Lights.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\LineTex.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\linkstat.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\LiteBall.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\litetype.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\LoadSave.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\LockDpth.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\LockTest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\loopback.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\luminanc.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\makeini.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ManualPanning.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\mapping.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\MatchMaking.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Matrices.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\MatrixPaletteSkinning.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\matsrc.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\media.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\memCheck.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\mempat.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\memtest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\memval.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Meshes.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Minnaert.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\mipflter.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\MirrorClip.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\misorbit.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\mixbins.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ModifyPixelShader.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\MotionBlur.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\MPalSkin.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\mstage1.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\mstage2.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\mstage3.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\mstage4.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\mstage5.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\MUConfig.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\MultiLit.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\MultiPass.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\MultiShader.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\muprod23.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\murw.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\netdata.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\netharness.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\NoSortAlphaBlend.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Notifier.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\obelisk.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\OnlineDashUpdate.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\OnlineDump.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\onlineharness.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Over.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\overdraw.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PaintEffect.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\palette0.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Patch.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\pb16000.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\peerclient.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\peerserver.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PerformanceCounters.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PerfTest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PerPixelLighting.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PerPixelLightingVS.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PersistDisplay.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\perspect.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PixelShader.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Play3DSound.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\playcd.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\playdvd.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PlayField.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PointSprites.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PointTex.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PolynomialTextureMaps.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ProjectedTexture.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PShader.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\pslights.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\psprite.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\psverify.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ptsprite.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\PushBuffer.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\readFile.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\reboot.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\RecoverHD.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\recovery.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\reenum.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\reflect0.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Refresh.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\regress.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\remotduke.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Rework.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Ripple.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\rteapot.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\rtpatch.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Rumble.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\sampleTest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ScreenTest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\SectionLoad.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\SetFilter.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\SetupOnline.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\sgdata.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ShaderSplicer.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ShadowBuffer.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ShadowVolume.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Simple.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\SimpleAuth.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\SimpleContentDownload.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\sinewave.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\skulls.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\slixbox.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\snowfall.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\SphereMap.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\srt.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\StateBlocks.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\StateShader.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\stats.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\stencil.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\stencil0.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\StencilDepth.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\StencilMirror.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\SwapCallback.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Swizzle.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\syncsrv.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\TechCertGame.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\terrain.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\TESTDS.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Texform.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\texgen.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\texgenxt.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\TexStage.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\textr1.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\textr2.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\textr3.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\textr4.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\textr5.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Textures.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\thumbposition.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Tiling.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\TLVClip.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Trees.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\TriC.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\TriCpp.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\TriVS.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\TriVSS.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\TriVSW.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\TrueTypeFont.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\tunnel.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\tvtest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\TwoSidedLighting.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ufmtest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\uftest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\unlock.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\UserClipPlane.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\v2dash.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\v2title.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VBBatch.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VBIB.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VertexBlend.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VertexShaders.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Vertices.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\vigil.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VirtualKeyboard.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VisibilityTest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\vistest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VoiceChat.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VoiceLoopBack.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VolTex.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\volume.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VolumeFog.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VolumeLight.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VolumeSprites.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VolumeTexture.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\vpshadr1.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VShader.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VSLights.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\VSTune.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\WaveBank.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\wbuffer.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\wcmp.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\WFVO.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\WinsockPeer.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\Wirefram.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\WMAInMemory.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\WMAStream.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\WMVCutScene.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\wrap1.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\WriteTest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\xbox11113.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\xboxdash.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\xboxkeys1.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\xboxkeys2.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XBRRServer.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\xidtest.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\xmoclnt.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\xmtaxbox.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\xnetperf.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\xnetstream.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\xnetstress.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XOnlineAddCachedUser.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XOnlineDash.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XOnlineGetLogonUsers.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XOnlineGetServiceInfo.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XOnlineGetUsers.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XOnlineLogon.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XOnlinePINDecodeInput.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XOnlinePINEndInput.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XOnlinePINStartInput.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XOnlineRemoveCachedUser.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XOnlineStartup.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XPRViewer.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XQuake.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XRay.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\XShell.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\xvoicemem.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\xvoiceperf.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\zbuffer.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\zcmp.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\dump\ZSprite.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\xboxkrnl.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\arcdkrnl.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\devkit\xbdm.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\devkit\cydrive.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\idw\xbshlext.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\idw\switcher.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\idw\strip.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\idw\DMTool.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
xcopy "%_NT386TREE%\idw\audanalyze.pdb" "%_NT386TREE%\Symbols.pri\%_BINPLACE_SUBDIR%\" /Y /H
echo.
exit /b