@if NOT DEFINED _echo echo off

REM *****************************
REM *** DO NOT EDIT THIS FILE ***
REM *****************************

REM *************************************************************************
REM *
REM * InitRazzle.cmd
REM *
REM * Initializes a directory creating a Razzle environment
REM *
REM * Usage:
REM *   InitRazzle drive [NTROOT \directory]
REM *
REM * Examples:
REM *   InitRazzle C: 
REM *   InitRazzle C: NTROOT \xbox
REM *
REM *************************************************************************

if "%1" == "-?" goto USAGE
if "%1" == "" goto USAGE
if "%2" == "" goto USAGE

setlocal

set _ntroot_=xbox

set _drive_=%1& shift
if /i "%1" == "ntroot" set _ntroot_=%2& shift& shift

xcopy /f %_drive_%\%_ntroot_%\private\developr\template %_drive_%\%_ntroot_%\private\developr\%username%\
cd /d %_drive_%\%_ntroot_%\private\developr\%username%
move cuep-sample.pri cuep.pri
move setenvp-sample.cmd setenvp.cmd
move setchkp-sample.cmd setchkp.cmd
move setfrep-sample.cmd setfrep.cmd
move tools-sample.ini tools.ini
set _ntdrive=%_drive_%
set _ntbindir=%_drive_%\%_ntroot_%

endlocal

goto DONE

:USAGE

echo.
echo InitRazzle {drive} [NTROOT \directory]
echo.

:DONE
